# Generated by Django 5.2.6 on 2026-09-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone / WhatsApp')),
                ('stay_type', models.CharField(choices=[('overnight', 'Overnight Stay (Check-in 12:00 PM, Check-out 11:00 AM)'), ('day_outing', 'Day Outing (Lunch, High Tea / Dinner, Pool)'), ('celebration', 'Family Celebration / Get-together / Event')], default='overnight', max_length=40, verbose_name='Stay Type')),
                ('check_in_date', models.DateField(blank=True, null=True, verbose_name='Check-in Date')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='Check-out Date')),
                ('number_of_guests', models.PositiveIntegerField(default=6, verbose_name='Guest Count')),
                ('message', models.TextField(blank=True, verbose_name='Requirements & Message')),
                ('status', models.CharField(choices=[('new', 'New Inquiry'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed Booking'), ('cancelled', 'Cancelled')], default='new', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Internal Staff Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Booking Inquiry',
                'verbose_name_plural': 'Booking Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Mark as Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VillaSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('outdoor', 'Pool & Outdoors'), ('bedrooms', 'Bedrooms & Dorm'), ('indoor', 'Living & Kitchen'), ('terrace', 'Sky Terraces')], default='outdoor', max_length=30)),
                ('subtitle', models.CharField(default='Luxury Feature', max_length=100)),
                ('location_info', models.CharField(default='Grace Ville, Saswad', max_length=150)),
                ('spec_1', models.CharField(blank=True, max_length=120)),
                ('spec_2', models.CharField(blank=True, max_length=120)),
                ('spec_3', models.CharField(blank=True, max_length=120)),
                ('spec_4', models.CharField(blank=True, max_length=120)),
                ('spec_5', models.CharField(blank=True, max_length=120)),
                ('image_rel_path', models.CharField(default='assets/images/property-01.jpg', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Villa Space',
                'verbose_name_plural': 'Villa Spaces',
                'ordering': ['order', 'id'],
            },
        ),
    ]
