# Generated by Django 5.2.17 on 2026-09-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginquiry',
            name='stay_type',
            field=models.CharField(choices=[('visit', 'Villa Visit / Site Inspection Appointment'), ('overnight', 'Overnight Stay (Check-in 12:00 PM, Check-out 11:00 AM)'), ('day_outing', 'Day Outing (Lunch, High Tea / Dinner, Pool)'), ('celebration', 'Family Celebration / Get-together / Event')], default='overnight', max_length=40, verbose_name='Stay Type'),
        ),
    ]
